In [1]:
import pandas as pd
import numpy as np

In [2]:
# Series() is used for 1D dataset
# series is represented as indexes and values
pd.Series([10,20,30,40,50,60,70,80])

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64

In [3]:
# Collections of Series
data_series = {'Column1' :pd.Series([10,20,30,40,50,60,70]),
               'Column2' :pd.Series([10,20,30,40,50,60,70])}

In [4]:
print(data_series)

{'Column1': 0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64, 'Column2': 0    10
1    20
2    30
3    40
4    50
5    60
6    70
dtype: int64}

In [5]:
# Display dataframe
pd.DataFrame(data_series)

   Column1  Column2
0       10       10
1       20       20
2       30       30
3       40       40
4       50       50
5       60       60
6       70       70

In [6]:
# Collections of Series
data_series = {'Column1' :pd.Series([10,20,30,40,50,60,70], index=['a','b','c','d','e','f','g']),
               'Column2' :pd.Series([10,20,30,40,50,60,70], index=['a','b','c','d','e','f','g'])}
# print(data_series)
pd.DataFrame(data_series)

   Column1  Column2
a       10       10
b       20       20
c       30       30
d       40       40
e       50       50
f       60       60
g       70       70

In [7]:
# Create a dataframe using dataset
autoprice_DF = pd.read_csv("D:/dataset/Automobile_price_data__Raw_.csv")
display(autoprice_DF)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [8]:
# .shape() returns (rows,columns)
autoprice_DF.shape

(205, 26)

In [9]:
# displays 1st 5 rows
autoprice_DF.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [10]:
autoprice_DF.tail()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625

In [11]:
autoprice_DF.columns

Index(['symboling', 'normalized-losses', 'make', 'fuel-type', 'aspiration',
       'num-of-doors', 'body-style', 'drive-wheels', 'engine-location',
       'wheel-base', 'length', 'width', 'height', 'curb-weight', 'engine-type',
       'num-of-cylinders', 'engine-size', 'fuel-system', 'bore', 'stroke',
       'compression-ratio', 'horsepower', 'peak-rpm', 'city-mpg',
       'highway-mpg', 'price'],
      dtype='object')

In [12]:
autoprice_DF.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   symboling          205 non-null    int64
 1   normalized-losses  205 non-null    object
 2   make               205 non-null    object
 3   fuel-type          205 non-null    object
 4   aspiration         205 non-null    object
 5   num-of-doors       205 non-null    object
 6   body-style         205 non-null    object
 7   drive-wheels       205 non-null    object
 8   engine-location    205 non-null    object
 9   wheel-base         205 non-null    float64
 10  length             205 non-null    float64
 11  width              205 non-null    float64
 12  height             205 non-null    float64
 13  curb-weight        205 non-null    int64
 14  engine-type        205 non-null    object
 15  num-of-cylinders   205 non-null    object
 16  engine-size        205 non-null    int64
 17  fuel-system        205 non-null    object
 18  bore               205 non-null    object
 19  stroke             205 non-null    object
 20  compression-ratio  205 non-null    float64
 21  horsepower         205 non-null    object
 22  peak-rpm           205 non-null    object
 23  city-mpg           205 non-null    int64
 24  highway-mpg        205 non-null    int64
 25  price              205 non-null    object
dtypes: float64(5), int64(5), object(16)
memory usage: 41.8+ KB

### Manipulation

In [13]:
# isnull() -> returns missing value as True and False for not null
autoprice_DF.isnull()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
201,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
202,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
203,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
204,False,False,False,False,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False

In [14]:
# notnull() -> returns missing value as Flase and True for not null
autoprice_DF.notnull()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
1,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
2,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
3,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
4,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
201,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
202,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
203,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
204,True,True,True,True,True,True,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True

In [15]:
# sum of missing rows
autoprice_DF.isnull().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [16]:
# sum of missing rows present in each column
autoprice_DF.isna().sum()

symboling            0
normalized-losses    0
make                 0
fuel-type            0
aspiration           0
num-of-doors         0
body-style           0
drive-wheels         0
engine-location      0
wheel-base           0
length               0
width                0
height               0
curb-weight          0
engine-type          0
num-of-cylinders     0
engine-size          0
fuel-system          0
bore                 0
stroke               0
compression-ratio    0
horsepower           0
peak-rpm             0
city-mpg             0
highway-mpg          0
price                0
dtype: int64

In [17]:
# describe by default applies to numerical columns
autoprice_DF.describe()

,symboling,wheel-base,length,width,height,curb-weight,engine-size,compression-ratio,city-mpg,highway-mpg
count,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000,205.000000
mean,0.834146,98.756585,174.049268,65.907805,53.724878,2555.565854,126.907317,10.142537,25.219512,30.751220
std,1.245307,6.021776,12.337289,2.145204,2.443522,520.680204,41.642693,3.972040,6.542142,6.886443
min,-2.000000,86.600000,141.100000,60.300000,47.800000,1488.000000,61.000000,7.000000,13.000000,16.000000
25%,0.000000,94.500000,166.300000,64.100000,52.000000,2145.000000,97.000000,8.600000,19.000000,25.000000
50%,1.000000,97.000000,173.200000,65.500000,54.100000,2414.000000,120.000000,9.000000,24.000000,30.000000
75%,2.000000,102.400000,183.100000,66.900000,55.500000,2935.000000,141.000000,9.400000,30.000000,34.000000
max,3.000000,120.900000,208.100000,72.300000,59.800000,4066.000000,326.000000,23.000000,49.000000,54.000000

In [18]:
# replace '?' by np.nan
# inplace=True (Apply changes in '?' by np.nan)
autoprice_DF.replace('?',np.nan,inplace=True)

In [19]:
autoprice_DF.isnull().sum()

symboling             0
normalized-losses    41
make                  0
fuel-type             0
aspiration            0
num-of-doors          2
body-style            0
drive-wheels          0
engine-location       0
wheel-base            0
length                0
width                 0
height                0
curb-weight           0
engine-type           0
num-of-cylinders      0
engine-size           0
fuel-system           0
bore                  4
stroke                4
compression-ratio     0
horsepower            2
peak-rpm              2
city-mpg              0
highway-mpg           0
price                 4
dtype: int64

In [20]:
# select 'price' column
autoprice_DF['price']

0      13495
1      16500
2      16500
3      13950
4      17450
       ...
200    16845
201    19045
202    21485
203    22470
204    22625
Name: price, Length: 205, dtype: object

In [21]:
# Selecting multiple columns
autoprice_DF[['make','peak-rpm','price','wheel-base']]

            make peak-rpm  price  wheel-base
0    alfa-romero     5000  13495        88.6
1    alfa-romero     5000  16500        88.6
2    alfa-romero     5000  16500        94.5
3           audi     5500  13950        99.8
4           audi     5500  17450        99.4
..           ...      ...    ...         ...
200        volvo     5400  16845       109.1
201        volvo     5300  19045       109.1
202        volvo     5500  21485       109.1
203        volvo     4800  22470       109.1
204        volvo     5400  22625       109.1

[205 rows x 4 columns]

In [22]:
autoprice_DF['price'] == np.nan

0      False
1      False
2      False
3      False
4      False
       ...
200    False
201    False
202    False
203    False
204    False
Name: price, Length: 205, dtype: bool

In [23]:
autoprice_DF[autoprice_DF['price'] == np.nan]

Empty DataFrame
Columns: [symboling, normalized-losses, make, fuel-type, aspiration, num-of-doors, body-style, drive-wheels, engine-location, wheel-base, length, width, height, curb-weight, engine-type, num-of-cylinders, engine-size, fuel-system, bore, stroke, compression-ratio, horsepower, peak-rpm, city-mpg, highway-mpg, price]
Index: []

[0 rows x 26 columns]

In [24]:
autoprice_DF[autoprice_DF['price'].isnull() == True]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN
44,1,NaN,isuzu,gas,std,two,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,NaN
45,0,NaN,isuzu,gas,std,four,sedan,fwd,front,94.5,...,90,2bbl,3.03,3.11,9.6,70,5400,38,43,NaN
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288,5750,17,28,NaN

In [25]:
# loc takes location
autoprice_DF.loc[0:11,]

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
5,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,15250
6,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,17710
7,1,NaN,audi,gas,std,four,wagon,fwd,front,105.8,...,136,mpfi,3.19,3.40,8.5,110,5500,19,25,18920
8,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,131,mpfi,3.13,3.40,8.3,140,5500,17,20,23875
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160,5500,16,22,NaN
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101,5800,23,29,16925

In [26]:
autoprice_DF.loc[:,['make','fuel-type','num-of-doors','body-style']]

            make fuel-type num-of-doors   body-style
0    alfa-romero       gas          two  convertible
1    alfa-romero       gas          two  convertible
2    alfa-romero       gas          two    hatchback
3           audi       gas         four        sedan
4           audi       gas         four        sedan
..           ...       ...          ...          ...
200        volvo       gas         four        sedan
201        volvo       gas         four        sedan
202        volvo       gas         four        sedan
203        volvo    diesel         four        sedan
204        volvo       gas         four        sedan

[205 rows x 4 columns]

In [27]:
# start index = 'make', stop_index = 'height'
autoprice_DF.loc[:,'make':'height']

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
201,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5
202,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
203,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5
204,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5

In [28]:
# slices data by row index and column index value
autoprice_DF.iloc[:,2:13]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,48.8
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3
...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
201,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,55.5
202,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,55.5
203,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5
204,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,55.5

In [29]:
# slicing of dataframe
autoprice_DF.iloc[2:15,2:13]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,height
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,52.4
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,54.3
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,54.3
5,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,53.1
6,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,55.7
7,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,55.7
8,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,55.9
9,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,52.0
10,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3
11,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3
12,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,54.3
13,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,54.3
14,bmw,gas,std,four,sedan,rwd,front,103.5,189.0,66.9,55.7

#### Sort Values
    * sort_values()

In [30]:
autoprice_DF.sort_values(by='make',ascending=False)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114,5400,19,25,22625
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162,5100,17,22,18950
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114,5400,24,28,15985
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
2,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
1,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495

In [31]:
autoprice_DF['horsepower'] = autoprice_DF['horsepower'].astype('float16')

In [32]:
autoprice_DF['horsepower'].sort_values

<bound method Series.sort_values of 0      111.0
1      111.0
2      154.0
3      102.0
4      115.0
       ...
200    114.0
201    160.0
202    134.0
203    106.0
204    114.0
Name: horsepower, Length: 205, dtype: float16>

In [39]:
autoprice_DF.sort_values(by='horsepower',ascending=False).head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
129,1,NaN,porsche,gas,std,two,hatchback,rwd,front,98.4,...,203,mpfi,3.94,3.11,10.0,288.0,5750,17,28,NaN
49,0,NaN,jaguar,gas,std,two,sedan,rwd,front,102.0,...,326,mpfi,3.54,2.76,11.5,262.0,5000,13,17,36000
128,3,NaN,porsche,gas,std,two,convertible,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,37028
127,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,34028
126,3,NaN,porsche,gas,std,two,hardtop,rwd,rear,89.5,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,32528
105,3,194,nissan,gas,turbo,two,hatchback,rwd,front,91.3,...,181,mpfi,3.43,3.27,7.8,200.0,5200,17,23,19699
73,0,NaN,mercedes-benz,gas,std,four,sedan,rwd,front,120.9,...,308,mpfi,3.80,3.35,8.0,184.0,4500,14,16,40960
74,1,NaN,mercedes-benz,gas,std,two,hardtop,rwd,front,112.0,...,304,mpfi,3.80,3.35,8.0,184.0,4500,14,16,45400
17,0,NaN,bmw,gas,std,four,sedan,rwd,front,110.0,...,209,mpfi,3.62,3.39,8.0,182.0,5400,15,20,36880
16,0,NaN,bmw,gas,std,two,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400,16,22,41315
15,0,NaN,bmw,gas,std,four,sedan,rwd,front,103.5,...,209,mpfi,3.62,3.39,8.0,182.0,5400,16,22,30760
48,0,NaN,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176.0,4750,15,19,35550
47,0,145,jaguar,gas,std,four,sedan,rwd,front,113.0,...,258,mpfi,3.63,4.17,8.1,176.0,4750,15,19,32250
75,1,NaN,mercury,gas,turbo,two,hatchback,rwd,front,102.7,...,140,mpfi,3.78,3.12,8.0,175.0,5000,19,24,16503
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18950
178,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200,20,24,16558
179,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,171,mpfi,3.27,3.35,9.3,161.0,5200,19,24,15998
106,1,231,nissan,gas,std,two,hatchback,rwd,front,99.2,...,181,mpfi,3.43,3.27,9.0,160.0,5200,19,25,18399
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045

In [38]:
autoprice_DF.sort_values(by=['make','horsepower'],ascending=[False,True]).head(20)

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800,26,27,22470
194,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,12940
195,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,13415
196,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,24,28,15985
197,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,141,mpfi,3.78,3.15,9.5,114.0,5400,24,28,16515
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045
198,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18420
199,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18950
182,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52.0,4800,37,46,7775
184,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,52.0,4800,37,46,7995
187,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,97,idi,3.01,3.40,23.0,68.0,4500,37,42,9495
192,0,NaN,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,97,idi,3.01,3.40,23.0,68.0,4500,33,38,13845
183,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85.0,5250,27,34,7975
185,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85.0,5250,27,34,8195
186,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,109,mpfi,3.19,3.40,9.0,85.0,5250,27,34,8495
193,0,NaN,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,109,mpfi,3.19,3.40,9.0,88.0,5500,25,31,12290
189,3,NaN,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,109,mpfi,3.19,3.40,8.5,90.0,5500,24,29,11595

In [40]:
#show unique values from a column
autoprice_DF['make'].unique()

array(['alfa-romero', 'audi', 'bmw', 'chevrolet', 'dodge', 'honda',
       'isuzu', 'jaguar', 'mazda', 'mercedes-benz', 'mercury',
       'mitsubishi', 'nissan', 'peugot', 'plymouth', 'porsche', 'renault',
       'saab', 'subaru', 'toyota', 'volkswagen', 'volvo'], dtype=object)

In [41]:
# Show 'make' frequency
autoprice_DF['make'].value_counts()

toyota           32
nissan           18
mazda            17
mitsubishi       13
honda            13
volkswagen       12
subaru           12
peugot           11
volvo            11
dodge             9
mercedes-benz     8
bmw               8
audi              7
plymouth          7
saab              6
porsche           5
isuzu             4
jaguar            3
chevrolet         3
alfa-romero       3
renault           2
mercury           1
Name: make, dtype: int64

In [44]:
autoprice_DF['make'].value_counts().sort_index()

alfa-romero       3
audi              7
bmw               8
chevrolet         3
dodge             9
honda            13
isuzu             4
jaguar            3
mazda            17
mercedes-benz     8
mercury           1
mitsubishi       13
nissan           18
peugot           11
plymouth          7
porsche           5
renault           2
saab              6
subaru           12
toyota           32
volkswagen       12
volvo            11
Name: make, dtype: int64

In [43]:
type(autoprice_DF['make'].value_counts())

pandas.core.series.Series

#### Drop()
    * Dropping Rows, Dropping columns

In [47]:
# axis = 0 : drop rows
autoprice_DF.drop([0,1,2,3,4,5,6,7,8])

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
9,0,NaN,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN
10,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16430
11,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16925
12,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,20970
13,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,21105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
201,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045
202,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485
203,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,145,idi,3.01,3.40,23.0,106.0,4800,26,27,22470
204,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625

In [49]:
# axis = 1 : drop columns
autoprice_DF.drop(['symboling', 'normalized-losses'], axis=1, inplace=True)

In [50]:
autoprice_DF.head()

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,13495
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,16500
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000,19,26,16500
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450

In [51]:
autoprice_DF.drop([0,1,2,3,4,5,6,7,8],axis=0).reset_index().drop('index',axis=1)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN
1,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16430
2,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,...,108,mpfi,3.50,2.80,8.8,101.0,5800,23,29,16925
3,bmw,gas,std,two,sedan,rwd,front,101.2,176.8,64.8,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,20970
4,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,21105
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
191,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
192,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045
193,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485
194,volvo,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,145,idi,3.01,3.40,23.0,106.0,4800,26,27,22470
195,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625

#### Filter Autoprice

In [56]:
autoprice_DF[autoprice_DF['make']=='audi']

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450
5,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110.0,5500,19,25,15250
6,audi,gas,std,four,sedan,fwd,front,105.8,192.7,71.4,...,136,mpfi,3.19,3.40,8.5,110.0,5500,19,25,17710
7,audi,gas,std,four,wagon,fwd,front,105.8,192.7,71.4,...,136,mpfi,3.19,3.40,8.5,110.0,5500,19,25,18920
8,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,...,131,mpfi,3.13,3.40,8.3,140.0,5500,17,20,23875
9,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN

In [55]:
autoprice_DF.filter(items=['make', 'audi'])

            make
0    alfa-romero
1    alfa-romero
2    alfa-romero
3           audi
4           audi
..           ...
200        volvo
201        volvo
202        volvo
203        volvo
204        volvo

[205 rows x 1 columns]

In [59]:
autoprice_DF[(autoprice_DF['make']=='audi') & (autoprice_DF['horsepower']>110)]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450
8,audi,gas,turbo,four,sedan,fwd,front,105.8,192.7,71.4,...,131,mpfi,3.13,3.40,8.3,140.0,5500,17,20,23875
9,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN

In [60]:
autoprice_DF[(autoprice_DF['make']=='audi') | (autoprice_DF['horsepower']>110)]

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,13495
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,16500
2,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,152,mpfi,2.68,3.47,9.0,154.0,5000,19,26,16500
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
199,volvo,gas,turbo,four,wagon,rwd,front,104.3,188.8,67.2,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18950
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
201,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,141,mpfi,3.78,3.15,8.7,160.0,5300,19,25,19045
202,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,173,mpfi,3.58,2.87,8.8,134.0,5500,18,23,21485
204,volvo,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114.0,5400,19,25,22625

#### Sampling of Data

In [65]:
autoprice_DF.sample(n=10)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
1,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,16500
198,volvo,gas,turbo,four,sedan,rwd,front,104.3,188.8,67.2,...,130,mpfi,3.62,3.15,7.5,162.0,5100,17,22,18420
5,audi,gas,std,two,sedan,fwd,front,99.8,177.3,66.3,...,136,mpfi,3.19,3.40,8.5,110.0,5500,19,25,15250
50,mazda,gas,std,two,hatchback,fwd,front,93.1,159.1,64.2,...,91,2bbl,3.03,3.15,9.0,68.0,5000,30,31,5195
182,volkswagen,diesel,std,two,sedan,fwd,front,97.3,171.7,65.5,...,97,idi,3.01,3.40,23.0,52.0,4800,37,46,7775
176,toyota,gas,std,four,sedan,fwd,front,102.4,175.6,66.5,...,122,mpfi,3.31,3.54,8.7,92.0,4200,27,32,10898
168,toyota,gas,std,two,hardtop,rwd,front,98.4,176.2,65.6,...,146,mpfi,3.62,3.50,9.3,116.0,4800,24,30,9639
9,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN
4,audi,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,136,mpfi,3.19,3.40,8.0,115.0,5500,18,22,17450
161,toyota,gas,std,four,hatchback,fwd,front,95.7,166.3,64.4,...,98,2bbl,3.19,3.03,9.0,70.0,4800,28,34,8358

In [67]:
autoprice_DF.sample(frac=0.2)

,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,length,width,...,engine-size,fuel-system,bore,stroke,compression-ratio,horsepower,peak-rpm,city-mpg,highway-mpg,price
111,peugot,gas,std,four,sedan,rwd,front,107.9,186.7,68.4,...,120,mpfi,3.46,2.19,8.4,95.0,5000,19,24,15580
166,toyota,gas,std,two,hatchback,rwd,front,94.5,168.7,64.0,...,98,mpfi,3.24,3.08,9.4,112.0,6600,26,29,9538
85,mitsubishi,gas,std,four,sedan,fwd,front,96.3,172.4,65.4,...,122,2bbl,3.35,3.46,8.5,88.0,5000,25,32,6989
40,honda,gas,std,four,sedan,fwd,front,96.5,175.4,62.5,...,110,1bbl,3.15,3.58,9.0,86.0,5800,27,33,10295
128,porsche,gas,std,two,convertible,rwd,rear,89.5,168.9,65.0,...,194,mpfi,3.74,2.90,9.5,207.0,5900,17,25,37028
176,toyota,gas,std,four,sedan,fwd,front,102.4,175.6,66.5,...,122,mpfi,3.31,3.54,8.7,92.0,4200,27,32,10898
27,dodge,gas,turbo,NaN,sedan,fwd,front,93.7,157.3,63.8,...,98,mpfi,3.03,3.39,7.6,102.0,5500,24,30,8558
97,nissan,gas,std,four,wagon,fwd,front,94.5,170.2,63.8,...,97,2bbl,3.15,3.29,9.4,69.0,5200,31,37,7999
94,nissan,gas,std,two,sedan,fwd,front,94.5,165.3,63.8,...,97,2bbl,3.15,3.29,9.4,69.0,5200,31,37,7299
16,bmw,gas,std,two,sedan,rwd,front,103.5,193.8,67.9,...,209,mpfi,3.62,3.39,8.0,182.0,5400,16,22,41315
112,peugot,diesel,turbo,four,sedan,rwd,front,107.9,186.7,68.4,...,152,idi,3.70,3.52,21.0,95.0,4150,28,33,16900
70,mercedes-benz,diesel,turbo,four,sedan,rwd,front,115.6,202.6,71.7,...,183,idi,3.58,3.64,21.5,123.0,4350,22,25,31600
29,dodge,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,...,156,mfi,3.60,3.90,7.0,145.0,5000,19,24,12964
83,mitsubishi,gas,turbo,two,hatchback,fwd,front,95.9,173.2,66.3,...,156,spdi,3.59,3.86,7.0,145.0,5000,19,24,14869
34,honda,gas,std,two,hatchback,fwd,front,93.7,150.0,64.0,...,92,1bbl,2.91,3.41,9.2,76.0,6000,30,34,7129
129,porsche,gas,std,two,hatchback,rwd,front,98.4,175.7,72.3,...,203,mpfi,3.94,3.11,10.0,288.0,5750,17,28,NaN
56,mazda,gas,std,two,hatchback,rwd,front,95.3,169.0,65.7,...,70,4bbl,NaN,NaN,9.4,101.0,6000,17,23,11845
159,toyota,diesel,std,four,hatchback,fwd,front,95.7,166.3,64.4,...,110,idi,3.27,3.35,22.5,56.0,4500,38,47,7788
91,nissan,gas,std,two,sedan,fwd,front,94.5,165.3,63.8,...,97,2bbl,3.15,3.29,9.4,69.0,5200,31,37,6649
162,toyota,gas,std,four,sedan,fwd,front,95.7,166.3,64.4,...,98,2bbl,3.19,3.03,9.0,70.0,4800,28,34,9258
0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,130,mpfi,3.47,2.68,9.0,111.0,5000,21,27,13495
48,jaguar,gas,std,four,sedan,rwd,front,113.0,199.6,69.6,...,258,mpfi,3.63,4.17,8.1,176.0,4750,15,19,35550
145,subaru,gas,turbo,four,sedan,4wd,front,97.0,172.0,65.4,...,108,mpfi,3.62,2.64,7.7,111.0,4800,24,29,11259
108,peugot,diesel,turbo,four,sedan,rwd,front,107.9,186.7,68.4,...,152,idi,3.70,3.52,21.0,95.0,4150,28,33,13200
183,volkswagen,gas,std,two,sedan,fwd,front,97.3,171.7,65.5,...,109,mpfi,3.19,3.40,9.0,85.0,5250,27,34,7975
26,dodge,gas,std,four,sedan,fwd,front,93.7,157.3,63.8,...,90,2bbl,2.97,3.23,9.4,68.0,5500,31,38,7609
100,nissan,gas,std,four,sedan,fwd,front,97.2,173.4,65.2,...,120,2bbl,3.33,3.47,8.5,97.0,5200,27,34,9549
3,audi,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,109,mpfi,3.19,3.40,10.0,102.0,5500,24,30,13950
154,toyota,gas,std,four,wagon,4wd,front,95.7,169.7,63.6,...,92,2bbl,3.05,3.03,9.0,62.0,4800,27,32,7898
9,audi,gas,turbo,two,hatchback,4wd,front,99.5,178.2,67.9,...,131,mpfi,3.13,3.40,7.0,160.0,5500,16,22,NaN
95,nissan,gas,std,two,hatchback,fwd,front,94.5,165.6,63.8,...,97,2bbl,3.15,3.29,9.4,69.0,5200,31,37,7799
37,honda,gas,std,two,hatchback,fwd,front,96.5,167.5,65.2,...,110,1bbl,3.15,3.58,9.0,86.0,5800,27,33,7895
188,volkswagen,gas,std,four,sedan,fwd,front,97.3,171.7,65.5,...,109,mpfi,3.19,3.40,10.0,100.0,5500,26,32,9995
200,volvo,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,141,mpfi,3.78,3.15,9.5,114.0,5400,23,28,16845
13,bmw,gas,std,four,sedan,rwd,front,101.2,176.8,64.8,...,164,mpfi,3.31,3.19,9.0,121.0,4250,21,28,21105
66,mazda,diesel,std,four,sedan,rwd,front,104.9,175.0,66.1,...,134,idi,3.43,3.64,22.0,72.0,4200,31,39,18344
136,saab,gas,turbo,two,hatchback,fwd,front,99.1,186.6,66.5,...,121,mpfi,3.54,3.07,9.0,160.0,5500,19,26,18150
130,renault,gas,std,four,wagon,fwd,front,96.1,181.5,66.5,...,132,mpfi,3.46,3.90,8.7,NaN,NaN,23,31,9295
118,plymouth,gas,std,two,hatchback,fwd,front,93.7,157.3,63.8,...,90,2bbl,2.97,3.23,9.4,68.0,5500,37,41,5572
18,chevrolet,gas,std,two,hatchback,fwd,front,88.4,141.1,60.3,...,61,2bbl,2.91,3.03,9.5,48.0,5100,47,53,5151
161,toyota,gas,std,four,hatchback,fwd,front,95.7,166.3,64.4,...,98,2bbl,3.19,3.03,9.0,70.0,4800,28,34,8358

In [70]:
#returns True for duplicate values
autoprice_DF.duplicated()

0      False
1      False
2      False
3      False
4      False
       ...
200    False
201    False
202    False
203    False
204    False
Length: 205, dtype: bool

In [71]:
#returns rows that matches duplicate condition
autoprice_DF[autoprice_DF.duplicated()]

Empty DataFrame
Columns: [make, fuel-type, aspiration, num-of-doors, body-style, drive-wheels, engine-location, wheel-base, length, width, height, curb-weight, engine-type, num-of-cylinders, engine-size, fuel-system, bore, stroke, compression-ratio, horsepower, peak-rpm, city-mpg, highway-mpg, price]
Index: []

[0 rows x 24 columns]

##### Create a 3 column dataframe using pandas series & pd.series and pd.DataFrame() - make sure to keep 2 rows having same values

In [103]:
data_series = {'Column1' :pd.Series([10,10,10,10,10,10,10]),
               'Column2' :pd.Series([10,10,10,10,10,10,10]),
               'Column3' :pd.Series([10,10,33,44,55,66,77,])}

In [104]:
k=pd.DataFrame(data_series)
k

   Column1  Column2  Column3
0       10       10       10
1       10       10       10
2       10       10       33
3       10       10       44
4       10       10       55
5       10       10       66
6       10       10       77

In [105]:
k.duplicated()

0    False
1     True
2    False
3    False
4    False
5    False
6    False
dtype: bool

In [106]:
k[k.duplicated()]

   Column1  Column2  Column3
1       10       10       10

In [113]:
k[k.duplicated()].index

Int64Index([1], dtype='int64')

#### Groupby()

In [119]:
autoprice_DF.groupby('make')[['city-mpg']].mean()

                city-mpg
make
alfa-romero    20.333333
audi           18.857143
bmw            19.375000
chevrolet      41.000000
dodge          28.000000
honda          30.384615
isuzu          31.000000
jaguar         14.333333
mazda          25.705882
mercedes-benz  18.500000
mercury        19.000000
mitsubishi     24.923077
nissan         27.000000
peugot         22.454545
plymouth       28.142857
porsche        17.400000
renault        23.000000
saab           20.333333
subaru         26.333333
toyota         27.500000
volkswagen     28.583333
volvo          21.181818

In [120]:
autoprice_DF.groupby('make')[['city-mpg']].mean().sort_values(by='city-mpg',ascending=False)

                city-mpg
make
chevrolet      41.000000
isuzu          31.000000
honda          30.384615
volkswagen     28.583333
plymouth       28.142857
dodge          28.000000
toyota         27.500000
nissan         27.000000
subaru         26.333333
mazda          25.705882
mitsubishi     24.923077
renault        23.000000
peugot         22.454545
volvo          21.181818
saab           20.333333
alfa-romero    20.333333
bmw            19.375000
mercury        19.000000
audi           18.857143
mercedes-benz  18.500000
porsche        17.400000
jaguar         14.333333

#### concat()

In [124]:
data_series1 = {'Column1' :pd.Series([10,10,10,10,10,10,10]),
               'Column2' :pd.Series([10,10,10,10,10,10,10]),
               'Column3' :pd.Series([10,10,33,44,55,66,77,])}
df1=pd.DataFrame(data_series1)

In [125]:
data_series2 = {'Column1' :pd.Series([11,12,13,14,15,16,17]),
               'Column2' :pd.Series([22,23,24,25,26,27,28])}
df2=pd.DataFrame(data_series2)

In [126]:
frame=[df1,df2]
res = pd.concat(frame)

In [127]:
res

   Column1  Column2  Column3
0       10       10     10.0
1       10       10     10.0
2       10       10     33.0
3       10       10     44.0
4       10       10     55.0
5       10       10     66.0
6       10       10     77.0
0       11       22      NaN
1       12       23      NaN
2       13       24      NaN
3       14       25      NaN
4       15       26      NaN
5       16       27      NaN
6       17       28      NaN